upd

diff --git a/.github/workflows/wonderful.yml b/.github/workflows/wonderful.yml
--- a/.github/workflows/wonderful.yml
+++ b/.github/workflows/wonderful.yml
@@ -10,18 +10,20 @@ jobs:
       - uses: actions/setup-python@v6
         with:
             python-version: '3.12'
-    
-      - name: Install Python dependencies
-        run: pip install pillow
       
       - name: Test wonderful toolchain installer
         run: |
-          curl -fsSL https://bread.codes/scripts/wonderful-linux.0.0.1.sh | bash
+          curl -fsSL https://bread.codes/scripts/wonderful-linux.0.0.2.sh | bash
           source /opt/wonderful/bin/wf-env
+          if ! command -v wf-pacman &> /dev/null; then
+              echo "wf-pacman could not be found!"
+              exit 1
+          fi
           git clone https://github.com/breadbored/butano-tutorial-series.git butano-tutorial-series
           cd butano-tutorial-series
           git submodule update --init --recursive
           cd chapter-1-getting-started
+          pip install pillow
           make
           if [ ! -f chapter-1-getting-started.gba ]; then
               echo "chapter-1-getting-started.gba does not exist!"
